api/urls.py
from django.urls import include, path

app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

contact_us/urls.py
from django.urls import path

from main.views import TemplateAPIView

from . import views

app_name = 'contact_us'


urlpatterns = [
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('contact/', TemplateAPIView.as_view(template_name='contact_us/index.html'), name='index'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .yasg import urlpatterns as swagger_url

admin_url = settings.ADMIN_URL

urlpatterns = [
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('', include('auth_app.urls')),
    path('', include('blog.urls')),
    path('', include('contact_us.urls')),
    path(f'{admin_url}/', admin.site.urls),
    path(f'{admin_url}/defender/', include('defender.urls')),
    path('api/', include('rest_framework.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += swagger_url

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if settings.ENABLE_SILK:
        urlpatterns.append(path('silk/', include('silk.urls', namespace='silk')))
    if settings.ENABLE_DEBUG_TOOLBAR:
        urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

contact_us/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from . import managers


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()

    class Meta:
        verbose_name = _('Feedback')

contact_us/views.py
import logging

from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny

from .serializers import FeedbackSerializer

logger = logging.getLogger(__name__)


class FeedbackView(CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = FeedbackSerializer

contact_us/templates/contact_us/index.html
{% extends "base.html" %}
{% block active_contact %}class="active"{% endblock active_contact %}

{% block header %}
{% include 'includes/header.html'  with selected='contact_us' %}
{% endblock header %}

{% block container %}

<h3 class="text-center">Contact us</h3><br/>

<div class="row">
  <div class="col-md-8">
    <form action="{% url 'contact_us:feedback' %}" method="post">
      {% csrf_token %}
      {% if not user.is_authenticated %}
      <input class="form-control" name="name" placeholder="Name..."/><br/>
      <input class="form-control" name="email" placeholder="E-mail..."/><br/>
      {% endif %}
      <textarea class="form-control" name="content" placeholder="How can we help you?"
                style="height:150px;"></textarea><br/>
      <input class="btn btn-primary" type="submit" value="Send"/><br/><br/>
    </form>
  </div>
  <div class="col-md-4">
    <b>Customer service:</b> <br/>
    Phone: +1 129 209 291<br/>
    E-mail: <a href="mailto:support@mysite.com">support@mysite.com</a><br/>
    <br/><br/>
    <b>Headquarter:</b><br/>
    Company Inc, <br/>
    Las vegas street 201<br/>
    55001 Nevada, USA<br/>
    Phone: +1 145 000 101<br/>
    <a href="mailto:usa@mysite.com">usa@mysite.com</a><br/>


    <br/><br/>
    <b>Hong kong:</b><br/>
    Company HK Litd, <br/>
    25/F.168 Queen<br/>
    Wan Chai District, Hong Kong<br/>
    Phone: +852 129 209 291<br/>
    <a href="mailto:hk@mysite.com">hk@mysite.com</a><br/>


  </div>
</div>
{% endblock container %}