api/urls.py
from django.urls import include, path

app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

auth_app/urls.py
from django.urls import path
from django.views.generic import TemplateView

from main.views import TemplateAPIView

app_name = 'auth_app'


urlpatterns = [
    path('login/', TemplateAPIView.as_view(template_name='auth_app/login.html'), name='login'),
    path('register/', TemplateAPIView.as_view(template_name='auth_app/sign_up.html'), name='sign_up'),
    path(
        'password-recovery/',
        TemplateAPIView.as_view(template_name='auth_app/reset_password_sent.html'),
        name='reset_email_sent',
    ),
    path('verify-email/', TemplateView.as_view(), name='account_verification'),
]

blog/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from main.views import TemplateAPIView

from . import views

app_name = 'blog'

router = DefaultRouter()
router.register('categories', views.CategoryViewSet, basename='categories')
router.register('posts', views.ArticleViewSet, basename='post')

urlpatterns = [
    path('blog/', TemplateAPIView.as_view(template_name='blog/post_list.html'), name='blog-list'),
]

urlpatterns += router.urls

contact_us/urls.py
from django.urls import path

from main.views import TemplateAPIView

from . import views

app_name = 'contact_us'


urlpatterns = [
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('contact/', TemplateAPIView.as_view(template_name='contact_us/index.html'), name='index'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .yasg import urlpatterns as swagger_url

admin_url = settings.ADMIN_URL

urlpatterns = [
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('', include('auth_app.urls')),
    path('', include('blog.urls')),
    path('', include('contact_us.urls')),
    path(f'{admin_url}/', admin.site.urls),
    path(f'{admin_url}/defender/', include('defender.urls')),
    path('api/', include('rest_framework.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += swagger_url

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if settings.ENABLE_SILK:
        urlpatterns.append(path('silk/', include('silk.urls', namespace='silk')))
    if settings.ENABLE_DEBUG_TOOLBAR:
        urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

templates/includes/footer.html
{% load static main blog %}
{% microservice_title as microservice_title %}
{% categories_list as categories %}
{% github_link as github_link %}

<footer>
  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-3 col-md-6">
        <div class="container">


          <div class="col-lg-3">
            <div class="cuadro_intro_hover " style="background-color:#cccccc;">
              <p style="text-align:center; margin-top:20px;">
                <img src="#" class="img-responsive" alt="">
              </p>
              <div class="caption">
                <div class="blur"></div>
                <div class="caption-text">
                  <h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">THIS IS H3</h3>
                  <p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
                  <a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
                </div>
              </div>
            </div>

          </div>
          <div class="col-lg-3">
            <div class="cuadro_intro_hover " style="background-color:#cccccc;">
              <p style="text-align:center; margin-top:20px;">
                <img src="#" class="img-responsive" alt="">
              </p>
              <div class="caption">
                <div class="blur"></div>
                <div class="caption-text">
                  <h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">THIS IS H3</h3>
                  <p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
                  <a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
                </div>
              </div>
            </div>

          </div>


          <div class="col-lg-3 col-md-6">
            <h3>Categories:</h3>
            <ul>
              {% for category in categories %}

              <li><a href=""><i class="fa fa-file"></i> {{ category.name }}</a></li>
              {% endfor %}

<!--              <li><a href=""><i class="fa fa-file"></i> News</a></li>-->
<!--              <li><a href=""><i class="fa fa-android"></i> Android</a></li>-->
<!--              <li><a href=""><i class="fa fa-code"></i> C#</a></li>-->
<!--              <li><a href=""><i class="fa fa-code"></i> Java</a></li>-->
<!--              <li><a href=""><i class="fa fa-book"></i> Books</a></li>-->
<!--              <li><a href=""><i class="fa fa-globe"></i> Web</a></li>-->
<!--              <li><a href=""><i class="fa fa-windows"></i> Windows</a></li>-->
            </ul>
          </div>

          <div class="col-lg-3 col-md-6">
            <h3>Contact:</h3>
            <p>Have a question or feedback? Contact me!</p>
            <p><a href="{% url 'contact_us:index' %}" title="Contact me!"><i class="fa fa-envelope"></i> Contact</a></p>
            <h3>Follow:</h3>


            <a href="" id="gh" target="_blank" title="Twitter">
              <span class="fa-stack fa-lg">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </span> Twitter
            </a>
            <a href="{{ github_link }}" target="_blank" title="GitHub">
              <span class="fa-stack fa-lg">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x"></i>
              </span> GitHub
            </a>

          </div>
          <br/>
          <a href="https://twitter.com/share" class="twitter-share-button" data-url="">Tweet</a>
          <!--          <script>-->
          <!--              !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');-->
          <!--          </script>-->
          <div class="g-plusone" data-annotation="inline" data-width="300" data-href=""></div>
          <br/>
          <hr>
          <p>Copyright © {{ microservice_title }} | <a href="">Privacy Policy</a> | <a href="">Terms of Use</a></p>


</footer>

templates/includes/header.html
{% load i18n main %}
{% microservice_title as microservice_title %}
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index' %}">{{ microservice_title }}</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li {% if selected == 'index' %}class="active"{% endif %}><a href="{% url 'index' %}">
      <i class="fa fa-home"></i> Home</a>
      </li>
      <li {% if selected == 'blog' %}class="active"{% endif %}><a href="{% url 'blog:blog-list' %}">
      <i class="fa fa-book"></i> Posts</a>
      </li>
      <li {% if selected == 'contact_us' %}class="active"{% endif %}><a href="{% url 'contact_us:index' %}">
      <i class="fa fa-envelope"></i> Contact</a>
      </li>
      <li {% if selected == 'about' %}class="active"{% endif %}>
      <a href=""></i> About</a>
      </li>

      <form class="navbar-form navbar-right">
        <input type="text" class="form-control col-lg-8" placeholder="Search...">
      </form>

    </ul>
    {% include 'includes/header_sign_status.html' %}
  </div>
  <!-- /.navbar-collapse -->

</div>
<!-- /.container -->

templates/includes/header_sign_status.html
{% load static i18n %}
{% if user.is_authenticated %}

<form id="logoutForm" action="{% url 'api:v1:auth_app:logout' %}" method="post" >
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">
            {% if user.is_staff %}
            <a target="_blank" style="text-decoration: none" href="{% url 'admin:index' %}"> {% trans 'Hello' %} {{ user.full_name }}!</a>
            {% else %}
                Hello {{ user.full_name }}!
            {% endif %}
            <a href="#"><i class="fas fa-user-circle"></i>{% trans 'Profile' %} </a>
        </span></li>
        <li><a href="#" id="logoutSubmit">{% trans 'Log off' %}</a></li>
    </ul>
</form>
{% else %}
<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'auth_app:login' %}">{% trans 'Sign in' %}</a></li>
    <li><a href="{% url 'auth_app:sign_up' %}">{% trans 'Sign up' %}</a></li>
</ul>
{% endif %}