api/urls.py
from django.urls import include, path

app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

api/v1/auth_app/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from . import views

app_name = 'auth_app'

urlpatterns = [
    path('sing-in/', views.LoginView.as_view(), name='sign-in'),
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('sign-up/verify/', views.VerifyEmailView.as_view(), name='sign-up-verify'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password/reset/', views.PasswordResetView.as_view(), name='reset-password'),
    path('password/reset/confirm/', views.PasswordResetConfirmView.as_view(), name='reset-password-confirm'),
    path('token/refresh/', TokenRefreshView.as_view()),
    path('token/verify/', TokenVerifyView.as_view()),
]

auth_app/urls.py
from django.urls import path
from django.views.generic import TemplateView

from main.views import TemplateAPIView

app_name = 'auth_app'


urlpatterns = [
    path('login/', TemplateAPIView.as_view(template_name='auth_app/login.html'), name='login'),
    path('register/', TemplateAPIView.as_view(template_name='auth_app/sign_up.html'), name='sign_up'),
    path(
        'password-recovery/',
        TemplateAPIView.as_view(template_name='auth_app/reset_password_sent.html'),
        name='reset_email_sent',
    ),
    path('verify-email/', TemplateView.as_view(), name='account_verification'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .yasg import urlpatterns as swagger_url

admin_url = settings.ADMIN_URL

urlpatterns = [
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('', include('auth_app.urls')),
    path('', include('blog.urls')),
    path('', include('contact_us.urls')),
    path(f'{admin_url}/', admin.site.urls),
    path(f'{admin_url}/defender/', include('defender.urls')),
    path('api/', include('rest_framework.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += swagger_url

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if settings.ENABLE_SILK:
        urlpatterns.append(path('silk/', include('silk.urls', namespace='silk')))
    if settings.ENABLE_DEBUG_TOOLBAR:
        urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

auth_app/forms.py
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from rest_framework.exceptions import ValidationError
from rest_framework.reverse import reverse_lazy

from main.services import CeleryService, UserService


class PassResetForm(PasswordResetForm):
    def get_reset_url(self, uid, token):
        path = "auth_app:password_reset_confirm"
        url = reverse_lazy(path, kwargs={'uidb64': uid, 'token': token})
        return settings.FRONTEND_SITE + str(url)

    def save(
        self,
        domain_override=None,
        subject_template_name='account/email/password_reset_subject.txt',
        email_template_name='account/email/password_reset_email.html',
        use_https=False,
        token_generator=default_token_generator,
        from_email=None,
        request=None,
        html_email_template_name='account/email/password_reset_email.html',
        extra_email_context=None,
        **kwargs
    ):
        """
        Generate a one-use only link for resetting password and send it to the user.
        """
        email = self.cleaned_data["email"]
        user = UserService.get_user(email=email)
        if not user:
            raise ValidationError({'email': _('User does not exist with this email')})
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = token_generator.make_token(user)
        url = self.get_reset_url(uid=uid, token=token)

        data = {
            'to_email': email,
            'content': {
                'user': user.get_full_name(),
                'reset_url': url,
            },
        }
        CeleryService.send_password_reset(data=data)

api/v1/auth_app/views.py
from dj_rest_auth import views as auth_views
from django.contrib.auth import logout as django_logout
from django.utils.translation import gettext_lazy as _
from rest_framework import status
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

from . import serializers
from .services import AuthAppService, full_logout


class SignUpView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = serializers.UserSignUpSerializer

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        service = AuthAppService()
        service.create_user(serializer.validated_data)
        return Response(
            {'detail': _('Confirmation email has been sent')},
            status=status.HTTP_201_CREATED,
        )


class LoginView(auth_views.LoginView):
    serializer_class = serializers.LoginSerializer


class LogoutView(auth_views.LogoutView):
    allowed_methods = ('POST', 'OPTIONS')

    def session_logout(self):
        django_logout(self.request)

    def logout(self, request):
        response = full_logout(request)
        return response


class PasswordResetView(GenericAPIView):
    serializer_class = serializers.PasswordResetSerializer
    permission_classes = (AllowAny,)

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response(
            {'detail': _('Password reset e-mail has been sent.')},
            status=status.HTTP_200_OK,
        )


class PasswordResetConfirmView(GenericAPIView):
    serializer_class = serializers.PasswordResetConfirmSerializer
    permission_classes = (AllowAny,)

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response(
            {'detail': _('Password has been reset with the new password.')},
            status=status.HTTP_200_OK,
        )


class VerifyEmailView(GenericAPIView):
    serializer_class = serializers.VerifyEmailSerializer
    permission_classes = (AllowAny,)

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response(
            {'detail': _('Email verified')},
            status=status.HTTP_200_OK,
        )

auth_app/views.py
import logging

from dj_rest_auth import views as auth_views
from django.contrib.auth import logout as django_logout
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny

from . import serializers
from .services import full_logout

logger = logging.getLogger(__name__)


class LoginView(auth_views.LoginView):
    serializer_class = serializers.LoginSerializer


class SignUpView(CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = serializers.UserSignUpSerializer


class PasswordResetView(auth_views.PasswordResetView):
    serializer_class = serializers.PasswordResetSerializer


class LogoutView(auth_views.LogoutView):
    allowed_methods = ('POST', 'OPTIONS')

    def session_logout(self):
        django_logout(self.request)

    def logout(self, request):
        self.session_logout()
        response = full_logout(request)
        return response

auth_app/templates/auth_app/includes/birthday.html
{% load i18n %}
<label for="birthday">{% trans 'Enter your date of birth:'%}</label>
<input type="date" name="birthday" id="birthday" class="form-control input-lg" min="">

auth_app/templates/auth_app/includes/forgot_password_modal.html
<!--modal-->
<div id="pwdModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h1 class="text-center">Reset Password?</h1>
      </div>
      <div class="modal-body">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="text-center">

                <p>If you have forgotten your password you can reset it here.</p>
                <div class="panel-body">
                  <fieldset>
                    <form id="forgotPasswordForm" method="post" action="{% url 'api:v1:auth_app:reset-password' %}">
                      {% csrf_token %}
                      <div id="emailForgotGroup" class="form-group">
                        <input class="form-control input-lg" placeholder="E-mail Address" name="email" type="email" required>
                      </div>
                      <input class="btn btn-lg btn-success btn-block" value="Reset password" type="submit">
                    </form>
                  </fieldset>
                  <div id="successPassReset" data-href="{% url 'auth_app:reset_email_sent' %}"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="col-md-12">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        </div>
      </div>
    </div>
  </div>
</div>

auth_app/templates/auth_app/includes/gender.html
<label>Gender : </label>
<label class="radio-inline">
  <input type="radio" name="gender" value="M" id=male/> Male
</label>
<label class="radio-inline">
  <input type="radio" name="gender" value="F" id=female/> Female
</label>

auth_app/templates/auth_app/includes/password.html
<input type="password" name="password1" value="" class="form-control input-lg" placeholder="Password"/>
<input type="password" name="password2" value="" class="form-control input-lg" placeholder="Confirm Password"/>

auth_app/templates/auth_app/includes/prevent_access.html
{% if user.is_authenticated %}
<script>
  window.location.replace("{% url 'index' %}")
</script>
{% endif %}